name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Build
        run: |
          docker build . -f Courses.API/Dockerfile -t isanjay112/courses:$GITHUB_RUN_NUMBER # will run buildx

#  build:
#
#    runs-on: ubuntu-latest
#    env:
#      DOCKER_REPOSITORY: isanjay112 # name of Docker Hub ID
#      IMAGE_NAME: courses
#      IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER
#
#  # Never amend commit again.
#    steps:
#    - uses: actions/checkout@v3
#    - name: Build the Docker image
#      run: docker build ./Courses.API --file ./Courses.API/Dockerfile --tag $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER


