name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    
    env:
      DOCKER_REPOSITORY: isanjay112 # name of Docker Hub ID
      IMAGE_NAME: courses
      IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build
        run: |
          docker build . -f Courses.API/Dockerfile -t $DOCKER_REPOSITORY/$IMAGE_NAME:0.0.$GITHUB_RUN_NUMBER
          
      - name: List Images
        run: |
          docker image ls
          
      - name: Push
        run: |
          docker push $DOCKER_REPOSITORY/$IMAGE_NAME:0.0.$GITHUB_RUN_NUMBER
